server:
  servlet:
    context-path: /weili
  port: 8080
  tomcat:
    protocol-header: x-forwarded-proto
  use-forward-headers: true
  address: 127.0.0.1

url:
  address: https://api.weixin.qq.com/sns/jscode2session
  appid: wx2be0b5437ef8e47d
  secret: 5c769c438086ca229242023718960742
  grant_type: authorization_code

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weili?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml



